### ISSUE TITLE
single-file version strategy not working

### ISSUE THREAD

**Issue by mephmanx** [troykinsella/concourse-artifactory-resource#6]
I cannot get this resource to upload a file to artifactory using a single-file versioning strategy no matter what combination of configuration I use.  I have tried what I believe is every combination of options and I keep getting file not found errors.  There is not really any documentation or examples on how to use it.  Could you point to working examples or add more to the documentation?  My job is pretty simple, build resource , upload to artifactory.  I define an optput folder for my job and the artifactory upload single file is in that directory.

**Comment by troykinsella** [comment]
Hi there!

I'm happy to try to help, but I'll be doing quite a bit of guessing without any configuration context or details to work from. If you can share some of your setup, it would help.

I assume you're wanting to generate a file in a task, and so that file will end up on a volume that you can feed into this resource. Let's say the volume is called `built-files` and the file is `foo.tgz`. I'll also assume that you have some need to react to publications of this file, so the following example uses the `single-file` version strategy.

Here's what your resource declaration might look like:

```
resource_types:
- name: generic-artifact
  type: docker-image
  source:
    repository: troykinsella/concourse-artifactory-resource

resources:
- name: foo-archive
  type: generic-artifact
  source:
    url: https://artifactory.you.com
    repository: the-repo-name
    api_key: ((repository_api_key))
    path: some-dir/foo.tgz # Noting that this is a single file path
    version_strategy: single-file
 ```

And here's what your archive generation and publication job might look like:

```
jobs:
- name: publish-foo
  plan:
  - get: git-branch
  - task: generate-foo
    file: path/to/generate-archive.yml
    params:
      FILE_NAME: foo.tgz
    input_mapping:
      source: git-branch
    output_mapping:
      output: built-files
  - put: foo-archive
    params:
      files: built-files
```

At this point if you're getting a `file not found` from the `put: foo-archive` step, maybe check that your file exists on the volume as expected, i.e. `built-files/foo.tgz`. Also important is that the name of the file you generate, `foo.tgz`, must match the file name in the `source.path` of the resource declaration.

To verify what your task is outputting, you can `fly hijack` the task container and look at the task output volume directory. If you want to check what is effectively being fed into the resource, similarly, you can hijack the put step and look around.

This said, if your job is solely to upload stuff to artifactory, and you have no need to react to changes to files, with a `get` step of this resource, the `none` version strategy may be more suitable for your need, because you can just match whatever files in a volume that you like with a glob pattern. Here's what this might look like:

```
resources:
- name: foo-archive
  type: generic-artifact
  source:
    url: https://artifactory.you.com
    repository: the-repo-name
    api_key: ((repository_api_key))
    path: some-dir # This is just the directory in which you want to publish files now
    version_strategy: none

jobs:
  ...
  - put: foo-archive
    params:
      files: built-files
      glob: "*.tgz"

```
